#version: '3.10'
#services:
#  app:
#    build: .
#    volumes:
#      - .:/app
#    ports:
#      - 8000:8000
#    image: bio-ta
#    container_name: django_container
#    depends_on:
#      - db
#    restart: always
#    command: ["./wait-for-it.sh", "db:3306", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
#  db:
#    container_name: "mysql_container"
#    image: mysql_db
#    restart: always
#    environment:
#      MYSQL_DATABASE: 'django-app-db'
#      MYSQL_ROOT_PASSWORD: '12345'
#    volumes:
#      - mysqlvol:/var/lib/mysql
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080
#volumes:
#    mysqlvol: null

version: '3.10'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: bio-ta
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000 
    depends_on:
      - db
    restart: on-failure:15
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${NAME}#'django-app-db'
      MYSQL_ROOT_PASSWORD: ${PASSWORD} 12345
    volumes:
      - ./data/mysql/dbb:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080