# Generated by Django 4.1 on 2022-08-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProteinID', models.IntegerField(unique=True)),
                ('Accessoin', models.TextField()),
                ('AverageMass', models.TextField(null=True)),
                ('Description', models.TextField()),
                ('ZeroHrProteinAbundance', models.IntegerField()),
                ('HalfHrProteinAbundance', models.IntegerField()),
                ('OneHrProteinAbundance', models.IntegerField()),
                ('TwoHrProteinAbundance', models.IntegerField()),
                ('ThreeHrProteinAbundance', models.IntegerField()),
                ('FourHrProteinAbundance', models.IntegerField()),
                ('FiveHrProteinAbundance', models.IntegerField()),
                ('SixHrProteinAbundance', models.IntegerField()),
                ('NineHrProteinAbundance', models.IntegerField()),
                ('TwelveHrProteinAbundance', models.IntegerField()),
                ('TwentyFourHrProteinAbundance', models.IntegerField()),
                ('CellularProcesses', models.TextField()),
                ('ProteinFunctions', models.TextField()),
                ('ReactomePathways', models.TextField()),
            ],
        ),
    ]
