# Generated by Django 4.1 on 2022-08-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_protein_onehrproteinabundance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='FiveHrProteinAbundance',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='protein',
            name='FourHrProteinAbundance',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='protein',
            name='HalfHrProteinAbundance',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='protein',
            name='NineHrProteinAbundance',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='protein',
            name='SixHrProteinAbundance',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='protein',
            name='ThreeHrProteinAbundance',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='protein',
            name='TwelveHrProteinAbundance',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='protein',
            name='TwentyFourHrProteinAbundance',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='protein',
            name='TwoHrProteinAbundance',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='protein',
            name='ZeroHrProteinAbundance',
            field=models.BigIntegerField(),
        ),
    ]
